### ISSUE TITLE
Javascript element error

### ISSUE THREAD

**Issue by npalbrecht** [motyar/fullscreen#1]
Hi, 

I am working on MacOs Sierra 10.12.5 and Chrome 61.0.3 or Safari 10.1.11.
When I just try to launch the plugin, I'm getting this error on the console : 

> Uncaught TypeError: elem[request] is not a function

My Javascript code is simple : 
`  $("body").append('<img src="https://www.w3schools.com/css/img_fjords.jpg" alt="" id="picture-test" />');
    $(document.body).on('click', '#picture-test', function(){
  		screenfull.toggle($(this));
  });
`

Did I miss something or is there a problem ? I've tried on both browsers and same results.

**Comment by motyar** [comment]
Please try the latest version of the code.
